<a href="https://colab.research.google.com/github/eisajanmohmand/NavTacBootCamp01/blob/main/navtavbootcampnumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [3]:
arr = np.array ([1,2,3])
print(arr)

[1 2 3]


In [12]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array ([[1,2,2],[4,5,6],[9,88,7]])
print(a)
print(type(a))

print(a,b)
print(type(b))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]] [[ 1  2  2]
 [ 4  5  6]
 [ 9 88  7]]
<class 'numpy.ndarray'>


In [13]:
!pip install numpy

In [14]:
import numpy as np

print(np.__version__)

2.0.2


In [26]:
import numpy as np

a = np.array (32)

b = np.array ([1,2])

c = np.array ([[1,2,3],[44,55,66]])

d =  np.array ([[[2,1,5,6],[3,4,9,8],[5,6,8,9]]])

print(a)
print(a.ndim)

print(b)
print(b.ndim)

print(c)
print(c.ndim)

print(d)
print(d.ndim)

32
0
[1 2]
1
[[ 1  2  3]
 [44 55 66]]
2
[[[2 1 5 6]
  [3 4 9 8]
  [5 6 8 9]]]
3


In [38]:
import numpy as np


arr = np.array([9,8,7,6], ndmin = 8)
print(arr)
print("number of dmin:",arr.ndim)

[[[[[[[[9 8 7 6]]]]]]]]
number of dmin: 8


In [42]:
arr = np.array ((1,2,3,4,5))
print(arr[0])
print(arr[1])
print(arr[2])
print(arr[3])
print(arr[0:3])
print(arr[0:])

1
2
3
4
[1 2 3]
[1 2 3 4 5]


In [49]:
a = np.array([1,2,3,4,5,6,7,8,9,10,20,30])
print(a[3]+a[5])
print(a[0]+a[8])
print(a[11]- a[10])

10
10
10


In [54]:
#dasfhhdsaiu

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:3])

[2 5]


In [59]:
a = np.array([1,2,3,4])
b = np.array(["apple"])
print(a.dtype)
print(b.dtype)

int64
<U5


In [65]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
'''import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype) '''

In [73]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[2]=0
print(arr)
print(x)

[1 2 0 4 5]
[1 2 3 4 5]


In [75]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
x = arr.view()
arr [5]=7
print(arr)
print(x)

[1 2 3 4 5 7]
[1 2 3 4 5 7]


In [82]:
import numpy as np

arr = np.array([[[1, 2, 3, 4,22],[1,2,3,4,5], [5, 6, 7, 8,33]]])

print(arr.shape)

(1, 3, 5)


In [85]:
import numpy as np
arr = np.array([1,2,3])

for z in arr:
  print(z)

1
2
3


In [84]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [89]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
  for y in x:
    for z in y:
      print(y)

[1 2 3]
[1 2 3]
[1 2 3]
[4 5 6]
[4 5 6]
[4 5 6]
[7 8 9]
[7 8 9]
[7 8 9]
[10 11 12]
[10 11 12]
[10 11 12]


*TASK*

In [94]:
import numpy as np

arr = np.arange(1,20)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [97]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5,6,7])
mean_value = arr.mean()
print(mean_value)

4.0


In [100]:
import numpy as np
a = np.array ([1,2,3,24])
mean_value = a.mean()
print(mean_value)

7.5
